### ISSUE TITLE
DOC: Add link to rse-web and/or rse-jekyll-web README from tutorials page

### ISSUE THREAD

**Issue by NickleDave** [rseng/rse#71]
as discussed here:
https://github.com/rhine3/bioacoustics-software/issues/3#issuecomment-1219894322

A user might want to know how to serve their own site from an `rse`-generated database

> You just need to generate the database, and then copy this repository to grab and update from it. https://github.com/rseng/web
> Or just copy this entirely :) https://github.com/rseng/rse-jekyll-web/
> That repository README has full instructions.
> I think perhaps we should provide a link to the repository I shared above here: https://rseng.github.io/rse/tutorials/index.html

Guessing you want a link to one of the READMEs, that will serve as a tutorial?
And that link should be added as another bullet point on tutorials/index?

**Comment by vsoch** [comment]
Yes! So here are the changes I think would be useful:

 - Under commands -> export jekyll site, provide a link to the rse-jekyll web as a template, and the main rseng/web as a full deployment of that.
 - Same under tutorials - but just provide the rse-jekyll-web

How does that sound?

**Comment by NickleDave** [comment]
Sounds good although I'm unclear what the "right" way to do things is.  

Is a user intended to generate the site with `rse export`, or should they be using one of the templates you linked to on https://github.com/rhine3/bioacoustics-software/issues/3 ?

If the user should generate the site with `rse export`, I'm not sure what the right way to add the links is; should the language be something like "you will run `rse export` that will produce a static site like the following: [link to site]"?

**Comment by vsoch** [comment]
You literally just need to make your spreadsheet and then clone this template (removing the previous database, etc.) https://github.com/rseng/rse-jekyll-web/. They can run rse export the first time to see how it works, but the automation in that repository is going to do it for them https://github.com/rseng/rse-jekyll-web/blob/5311b3c9702379322e19cc6d70fe9726c5604fc1/.github/workflows/update.yaml#L31-L35 so technically you can just make your Google Sheet, edit the link to it, and push to GitHub and call it a day.

**Comment by NickleDave** [comment]
Ahhhhhhhhh ok I am finally understanding now.  

I should have actually read the [rse-jekyll-web](https://github.com/rseng/rse-jekyll-web) README then, shouldn't I?  

When you said "copy" I thought you meant literally "`cp` this code into your feature branch", not "fork this repo because it will do all the work for you".

So you *really* want the `export` command docs to say something like 
"To see an example of a site that is created by automated runs of the `export --jekyll-web` command, please visit: https://github.com/rseng/web`. If you are `import`ing from a spreadsheet, and you want to automate updating a site built from that spreadsheet, please see the example at https://github.com/rseng/rse-jekyll-web/. As explained in the README, you can fork this repo and change the url to your spreadsheet, which will run `export` with GitHub Actions, avoiding the need for you to run the `export` command manually."

And then use similar language in the tutorial page, "To see how you can simply fork a repo to get automated updating from a Google spreadsheet, please see this README: [link]"

Correct?

**Comment by vsoch** [comment]
Right, so I think all of that information is in the rse-jekyll-web readme, so to not duplicate we should link to it (with some minimal context). If there are bits missing we can update them there.

**Comment by vsoch** [comment]
Fixed with https://github.com/rseng/rse/pull/75
