### ISSUE TITLE
DOC: Revise / add screenshot of how to share google sheets for `rse import`

### ISSUE THREAD

**Issue by NickleDave** [rseng/rse#74]
The `rse import` command docs are very thorough (if only a user reads them :innocent:) but the explanation of how to share the sheet might be a bit confusing since there are two places that say "share": (1) a big vibrantly-colored button in the upper right, which is not what you are referring to, and (2) one tiny word under the File dropdown on the menu bar, that you are referring to.

I thought it was (1) and not (2) and spent a while staring at the box for (2) trying to figure out what I was missing.

One way to make this clearer would be to change this
```
Share -> Publish to Web -> Form Responses 1 (or the sheet name in first dropdown) -> Comma-separated value (csv) (second dropdown)
```
to this
```
File -> Share -> Publish to Web -> Form Responses 1 (or the sheet name in first dropdown) -> Comma-separated value (csv) (second dropdown)
```

Another way would be to add a screenshot with arrows saying "not this" and "this" (with the dropdown showing)

**Comment by vsoch** [comment]
That would work for me! Would you care to open a PR to make this tweak?

**Comment by NickleDave** [comment]
Will do

**Comment by vsoch** [comment]
Fixed with https://github.com/rseng/rse/pull/75
